In [40]:
# Install Libraries
!pip install kagglehub
!pip install kaggle
!pip install pandas

Requirement already satisfied: kagglehub in c:\users\odiss\anaconda3\lib\site-packages (0.3.4)
Requirement already satisfied: packaging in c:\users\odiss\anaconda3\lib\site-packages (from kagglehub) (24.1)
Requirement already satisfied: requests in c:\users\odiss\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\odiss\anaconda3\lib\site-packages (from kagglehub) (4.66.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\odiss\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\odiss\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\odiss\anaconda3\lib\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\odiss\anaconda3\lib\site-packages (from requests->kagglehub) (2024.8.30)
Requirement already satisfied: colorama in c:\users\odiss\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Requirement already satisfied: kaggle in c:\users\odiss\anaconda3\lib\site-packages (1.6.17)
Requirement already satisfied: six>=1.10 in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (4.66.5)
Requirement already satisfied: python-slugify in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in c:\users\odiss\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\odiss\anaconda3\lib\site-packages (from bleach->kaggle) (24.1)
Requirement already satisfied: webencodings in c:\users\odiss\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\odiss\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\odiss\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\odiss\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\odiss\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Requirement already satisfied: pandas in c:\users\odiss\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\odiss\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\odiss\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\odiss\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\odiss\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\odiss\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [41]:
# Import Libraries
import kagglehub
import os
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("sumaiaparveenshupti/los-angeles-crime-data-20102020")
print("Path to dataset files:", path)

Path to dataset files: C:\Users\odiss\.cache\kagglehub\datasets\sumaiaparveenshupti\los-angeles-crime-data-20102020\versions\3

In [42]:
# List all files in the specified directory and store the file names in the `files` list
files = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]
print("Files in directory:", files)

Files in directory: ['Crime_Data_from_2010_to_2019.csv', 'Crime_Data_from_2020_to_Present.csv']

In [43]:
# Load the first CSV file into a DataFrame
la_crime_data_2010_to_2019 = pd.read_csv(os.path.join(path, files[0]))
la_crime_data_2010_to_2019

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2117584,190608903,03/28/2019 12:00:00 AM,03/28/2019 12:00:00 AM,400,6,Hollywood,644,1,648,ARSON,...,IC,Invest Cont,648.0,NaN,NaN,NaN,1400 N LA BREA AV,NaN,34.0962,-118.3490
2117585,190715222,08/15/2019 12:00:00 AM,08/14/2019 12:00:00 AM,1810,7,Wilshire,701,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),...,IC,Invest Cont,331.0,NaN,NaN,NaN,WILLOUGHBY AV,ORLANDO AV,34.0871,-118.3732
2117586,192004409,01/06/2019 12:00:00 AM,01/06/2019 12:00:00 AM,2100,20,Olympic,2029,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,IC,Invest Cont,930.0,NaN,NaN,NaN,6TH,VIRGIL,34.0637,-118.2870
2117587,191716777,10/17/2019 12:00:00 AM,10/16/2019 12:00:00 AM,1800,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2117588,190805435,02/01/2019 12:00:00 AM,02/01/2019 12:00:00 AM,1615,8,West LA,852,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [44]:
# Load the second CSV file into a DataFrame
la_crime_data_2020_to_2021 = pd.read_csv(os.path.join(path, files[1]))
la_crime_data_2020_to_2021

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,201220752,09/16/2020 12:00:00 AM,09/16/2020 12:00:00 AM,1230,12,77th Street,1259,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,700 E 73RD ST,NaN,33.9739,-118.2630
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276579,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,4,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,1400 S DE LA TORRE WY,NaN,34.0166,-118.2058
276580,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,20,Olympic,2056,2,888,TRESPASSING,...,IC,Invest Cont,888.0,998.0,NaN,NaN,900 S BERENDO ST,NaN,34.0527,-118.2937
276581,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,12,77th Street,1218,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,58TH ST,FIGUEROA ST,33.9897,-118.2827
276582,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,5,Harbor,564,2,434,FALSE IMPRISONMENT,...,AA,Adult Arrest,434.0,NaN,NaN,NaN,200 W 2ND ST,NaN,33.7424,-118.2814
276583,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,20,Olympic,2034,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,3300 W 8TH ST,NaN,34.0596,-118.3022

In [45]:
# Combine datasets
la_crime_data_2010_to_2021 = pd.concat([la_crime_data_2010_to_2019, la_crime_data_2020_to_2021], ignore_index=True)
la_crime_data_2010_to_2021

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON,AREA
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13.0,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695,NaN
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14.0,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962,NaN
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13.0,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524,NaN
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6.0,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295,NaN
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1.0,Central,176,1,122,"RAPE, ATTEMPTED",...,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394168,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,NaN,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,Invest Cont,510.0,NaN,NaN,NaN,1400 S DE LA TORRE WY,NaN,34.0166,-118.2058,4.0
2394169,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,NaN,Olympic,2056,2,888,TRESPASSING,...,Invest Cont,888.0,998.0,NaN,NaN,900 S BERENDO ST,NaN,34.0527,-118.2937,20.0
2394170,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,NaN,77th Street,1218,1,510,VEHICLE - STOLEN,...,Invest Cont,510.0,NaN,NaN,NaN,58TH ST,FIGUEROA ST,33.9897,-118.2827,12.0
2394171,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,NaN,Harbor,564,2,434,FALSE IMPRISONMENT,...,Adult Arrest,434.0,NaN,NaN,NaN,200 W 2ND ST,NaN,33.7424,-118.2814,5.0
2394172,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,NaN,Olympic,2034,1,510,VEHICLE - STOLEN,...,Invest Cont,510.0,NaN,NaN,NaN,3300 W 8TH ST,NaN,34.0596,-118.3022,20.0

In [46]:
# Inspect column names
la_crime_data_2010_to_2021.columns.tolist()

['DR_NO',
 'Date Rptd',
 'DATE OCC',
 'TIME OCC',
 'AREA ',
 'AREA NAME',
 'Rpt Dist No',
 'Part 1-2',
 'Crm Cd',
 'Crm Cd Desc',
 'Mocodes',
 'Vict Age',
 'Vict Sex',
 'Vict Descent',
 'Premis Cd',
 'Premis Desc',
 'Weapon Used Cd',
 'Weapon Desc',
 'Status',
 'Status Desc',
 'Crm Cd 1',
 'Crm Cd 2',
 'Crm Cd 3',
 'Crm Cd 4',
 'LOCATION',
 'Cross Street',
 'LAT',
 'LON',
 'AREA']

In [47]:
# Removed unnecessary spacing
la_crime_data_2010_to_2021.columns = la_crime_data_2010_to_2021.columns.str.strip()

# Dropped crime code columns 2, 3, 4
la_crime_data_2010_to_2021 = la_crime_data_2010_to_2021.drop(columns=['Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4'])
la_crime_data_2010_to_2021

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,LOCATION,Cross Street,LAT,LON,AREA
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13.0,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,NaN,NaN,AA,Adult Arrest,900.0,300 E GAGE AV,NaN,33.9825,-118.2695,NaN
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14.0,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,NaN,NaN,IC,Invest Cont,740.0,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962,NaN
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13.0,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,NaN,NaN,IC,Invest Cont,946.0,1300 E 21ST ST,NaN,34.0224,-118.2524,NaN
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6.0,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,102.0,HAND GUN,IC,Invest Cont,900.0,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295,NaN
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1.0,Central,176,1,122,"RAPE, ATTEMPTED",...,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,122.0,8TH ST,SAN PEDRO ST,34.0387,-118.2488,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394168,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,NaN,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,NaN,NaN,IC,Invest Cont,510.0,1400 S DE LA TORRE WY,NaN,34.0166,-118.2058,4.0
2394169,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,NaN,Olympic,2056,2,888,TRESPASSING,...,NaN,NaN,IC,Invest Cont,888.0,900 S BERENDO ST,NaN,34.0527,-118.2937,20.0
2394170,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,NaN,77th Street,1218,1,510,VEHICLE - STOLEN,...,NaN,NaN,IC,Invest Cont,510.0,58TH ST,FIGUEROA ST,33.9897,-118.2827,12.0
2394171,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,NaN,Harbor,564,2,434,FALSE IMPRISONMENT,...,200.0,KNIFE WITH BLADE 6INCHES OR LESS,AA,Adult Arrest,434.0,200 W 2ND ST,NaN,33.7424,-118.2814,5.0
2394172,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,NaN,Olympic,2034,1,510,VEHICLE - STOLEN,...,NaN,NaN,IC,Invest Cont,510.0,3300 W 8TH ST,NaN,34.0596,-118.3022,20.0

In [48]:
# Remove duplicate rows from the DataFrame
la_crime_data_2010_to_2021 = la_crime_data_2010_to_2021.drop_duplicates()
la_crime_data_2010_to_2021

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,LOCATION,Cross Street,LAT,LON,AREA
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13.0,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,NaN,NaN,AA,Adult Arrest,900.0,300 E GAGE AV,NaN,33.9825,-118.2695,NaN
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14.0,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,NaN,NaN,IC,Invest Cont,740.0,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962,NaN
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13.0,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,NaN,NaN,IC,Invest Cont,946.0,1300 E 21ST ST,NaN,34.0224,-118.2524,NaN
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6.0,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,102.0,HAND GUN,IC,Invest Cont,900.0,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295,NaN
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1.0,Central,176,1,122,"RAPE, ATTEMPTED",...,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,122.0,8TH ST,SAN PEDRO ST,34.0387,-118.2488,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394168,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,NaN,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,NaN,NaN,IC,Invest Cont,510.0,1400 S DE LA TORRE WY,NaN,34.0166,-118.2058,4.0
2394169,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,NaN,Olympic,2056,2,888,TRESPASSING,...,NaN,NaN,IC,Invest Cont,888.0,900 S BERENDO ST,NaN,34.0527,-118.2937,20.0
2394170,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,NaN,77th Street,1218,1,510,VEHICLE - STOLEN,...,NaN,NaN,IC,Invest Cont,510.0,58TH ST,FIGUEROA ST,33.9897,-118.2827,12.0
2394171,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,NaN,Harbor,564,2,434,FALSE IMPRISONMENT,...,200.0,KNIFE WITH BLADE 6INCHES OR LESS,AA,Adult Arrest,434.0,200 W 2ND ST,NaN,33.7424,-118.2814,5.0
2394172,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,NaN,Olympic,2034,1,510,VEHICLE - STOLEN,...,NaN,NaN,IC,Invest Cont,510.0,3300 W 8TH ST,NaN,34.0596,-118.3022,20.0

In [49]:
# Fill NaNs with 0
la_crime_data_2010_to_2021.fillna(0)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,LOCATION,Cross Street,LAT,LON,AREA
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13.0,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,0.0,0,AA,Adult Arrest,900.0,300 E GAGE AV,0,33.9825,-118.2695,0.0
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14.0,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,0.0,0,IC,Invest Cont,740.0,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962,0.0
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13.0,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,0.0,0,IC,Invest Cont,946.0,1300 E 21ST ST,0,34.0224,-118.2524,0.0
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6.0,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,102.0,HAND GUN,IC,Invest Cont,900.0,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295,0.0
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1.0,Central,176,1,122,"RAPE, ATTEMPTED",...,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,122.0,8TH ST,SAN PEDRO ST,34.0387,-118.2488,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394168,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,0.0,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,0.0,0,IC,Invest Cont,510.0,1400 S DE LA TORRE WY,0,34.0166,-118.2058,4.0
2394169,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,0.0,Olympic,2056,2,888,TRESPASSING,...,0.0,0,IC,Invest Cont,888.0,900 S BERENDO ST,0,34.0527,-118.2937,20.0
2394170,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,0.0,77th Street,1218,1,510,VEHICLE - STOLEN,...,0.0,0,IC,Invest Cont,510.0,58TH ST,FIGUEROA ST,33.9897,-118.2827,12.0
2394171,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,0.0,Harbor,564,2,434,FALSE IMPRISONMENT,...,200.0,KNIFE WITH BLADE 6INCHES OR LESS,AA,Adult Arrest,434.0,200 W 2ND ST,0,33.7424,-118.2814,5.0
2394172,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,0.0,Olympic,2034,1,510,VEHICLE - STOLEN,...,0.0,0,IC,Invest Cont,510.0,3300 W 8TH ST,0,34.0596,-118.3022,20.0

In [50]:
# Check the data types of each column
print(la_crime_data_2010_to_2021.dtypes)

DR_NO               int64
Date Rptd          object
DATE OCC           object
TIME OCC            int64
AREA              float64
AREA NAME          object
Rpt Dist No         int64
Part 1-2            int64
Crm Cd              int64
Crm Cd Desc        object
Mocodes            object
Vict Age            int64
Vict Sex           object
Vict Descent       object
Premis Cd         float64
Premis Desc        object
Weapon Used Cd    float64
Weapon Desc        object
Status             object
Status Desc        object
Crm Cd 1          float64
LOCATION           object
Cross Street       object
LAT               float64
LON               float64
AREA              float64
dtype: object

In [51]:
# Convert LAT and LON columns to geometry tuples
la_crime_data_2010_to_2021['Geometry'] = la_crime_data_2010_to_2021.apply(
    lambda row: (row['LON'], row['LAT']), axis=1
)
# Move the geometry column to be right after longitude
lon_index = la_crime_data_2010_to_2021.columns.get_loc('LON')
la_crime_data_2010_to_2021.insert(lon_index + 1, 'Geometry', la_crime_data_2010_to_2021.pop('Geometry'))
la_crime_data_2010_to_2021

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Weapon Desc,Status,Status Desc,Crm Cd 1,LOCATION,Cross Street,LAT,LON,Geometry,AREA
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13.0,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,NaN,AA,Adult Arrest,900.0,300 E GAGE AV,NaN,33.9825,-118.2695,"(-118.2695, 33.9825)",NaN
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14.0,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,NaN,IC,Invest Cont,740.0,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962,"(-118.3962, 33.9599)",NaN
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13.0,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,NaN,IC,Invest Cont,946.0,1300 E 21ST ST,NaN,34.0224,-118.2524,"(-118.2524, 34.0224)",NaN
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6.0,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,HAND GUN,IC,Invest Cont,900.0,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295,"(-118.3295, 34.1016)",NaN
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1.0,Central,176,1,122,"RAPE, ATTEMPTED",...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,122.0,8TH ST,SAN PEDRO ST,34.0387,-118.2488,"(-118.2488, 34.0387)",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394168,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,NaN,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,NaN,IC,Invest Cont,510.0,1400 S DE LA TORRE WY,NaN,34.0166,-118.2058,"(-118.2058, 34.0166)",4.0
2394169,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,NaN,Olympic,2056,2,888,TRESPASSING,...,NaN,IC,Invest Cont,888.0,900 S BERENDO ST,NaN,34.0527,-118.2937,"(-118.2937, 34.0527)",20.0
2394170,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,NaN,77th Street,1218,1,510,VEHICLE - STOLEN,...,NaN,IC,Invest Cont,510.0,58TH ST,FIGUEROA ST,33.9897,-118.2827,"(-118.2827, 33.9897)",12.0
2394171,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,NaN,Harbor,564,2,434,FALSE IMPRISONMENT,...,KNIFE WITH BLADE 6INCHES OR LESS,AA,Adult Arrest,434.0,200 W 2ND ST,NaN,33.7424,-118.2814,"(-118.2814, 33.7424)",5.0
2394172,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,NaN,Olympic,2034,1,510,VEHICLE - STOLEN,...,NaN,IC,Invest Cont,510.0,3300 W 8TH ST,NaN,34.0596,-118.3022,"(-118.3022, 34.0596)",20.0