In [ ]:
!pip install kagglehub

!pip install kaggle

Requirement already satisfied: kagglehub in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.3.4)
Requirement already satisfied: packaging in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kagglehub) (24.2)
Requirement already satisfied: requests in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kagglehub) (4.67.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kagglehub) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kagglehub) (2024.8.30)
Requirement already satisfied: colorama in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\odiss\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting kaggle
  Downloading kaggle-1.6.17.tar.gz (82 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six>=1.10 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (4.67.0)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: urllib3 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaggle) (2.2.3)
Collecting bleach (from kaggle)
  Downloading bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting webencodings (from bleach->kaggle)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->kaggle) (3.10)
Requirement already satisfied: colorama in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm->kaggle) (0.4.6)
Downloading bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: kaggle
  Building wheel for kaggle (pyproject.toml): started
  Building wheel for kaggle (pyproject.toml): finished with status 'done'
  Created wheel for kaggle: filename=kaggle-1.6.17-py3-none-any.whl size=105797 sha256=a3edef6442b491a577fdfc6fc3439a7ab57eb8dd9ab4a468691a23a7096be49d
  Stored in directory: c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\ff\55\fb\b27a466be754d2a06ffe0e37b248d844f090a63b51becea85d
Successfully built kaggle
Installing collected packages: webencodings, text-unidecode, python-slugify, bleach, kaggle
Successfully installed bleach-6.2.0 kaggle-1.6.17 python-slugify-8.0.4 text-unidecode-1.3 webencodings-0.5.1

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\odiss\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.23.2 (from pandas)
  Downloading numpy-2.1.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\odiss\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.6 MB 8.5 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.6 MB 4.2 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.6 MB 4.1 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/11.6 MB 3.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.6 MB 4.0 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.6 MB 4.1 MB/s eta 0:00:02
   ------------------ --------------------- 5.5/11.6 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.6 MB 4.2 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.6 MB 4.2 MB/s eta 0:00:01
   ---------------------------- ----------- 8.4/11.6 MB 4.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.6 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.6 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.6 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.6 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 3.9 MB/s eta 0:00:00
Downloading numpy-2.1.3-cp311-cp311-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.9 MB 3.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.9 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.9/12.9 MB 4.5 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.9 MB 4.7 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.9 MB 4.6 MB/s eta 0:00:02
   ----------------- ---------------------- 5.8/12.9 MB 4.6 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.9 MB 4.6 MB/s eta 0:00:02
   ---------------------- ----------------- 7.3/12.9 MB 4.5 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.9 MB 4.5 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.9 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.9 MB 4.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/12.9 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.9 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.9 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 4.1 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.3 pandas-2.2.3 pytz-2024.2 tzdata-2024.2

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\odiss\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [6]:
import kagglehub
import os
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("sumaiaparveenshupti/los-angeles-crime-data-20102020")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\odiss\.cache\kagglehub\datasets\sumaiaparveenshupti\los-angeles-crime-data-20102020\versions\3

In [7]:
files = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]

print("Files in directory:", files)

Files in directory: ['Crime_Data_from_2010_to_2019.csv', 'Crime_Data_from_2020_to_Present.csv']

In [9]:
df_0 = pd.read_csv(os.path.join(path, files[0]))
df_0

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2117584,190608903,03/28/2019 12:00:00 AM,03/28/2019 12:00:00 AM,400,6,Hollywood,644,1,648,ARSON,...,IC,Invest Cont,648.0,NaN,NaN,NaN,1400 N LA BREA AV,NaN,34.0962,-118.3490
2117585,190715222,08/15/2019 12:00:00 AM,08/14/2019 12:00:00 AM,1810,7,Wilshire,701,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),...,IC,Invest Cont,331.0,NaN,NaN,NaN,WILLOUGHBY AV,ORLANDO AV,34.0871,-118.3732
2117586,192004409,01/06/2019 12:00:00 AM,01/06/2019 12:00:00 AM,2100,20,Olympic,2029,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,IC,Invest Cont,930.0,NaN,NaN,NaN,6TH,VIRGIL,34.0637,-118.2870
2117587,191716777,10/17/2019 12:00:00 AM,10/16/2019 12:00:00 AM,1800,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2117588,190805435,02/01/2019 12:00:00 AM,02/01/2019 12:00:00 AM,1615,8,West LA,852,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [10]:
df_1 = pd.read_csv(os.path.join(path, files[1]))
df_1

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,201220752,09/16/2020 12:00:00 AM,09/16/2020 12:00:00 AM,1230,12,77th Street,1259,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,700 E 73RD ST,NaN,33.9739,-118.2630
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276579,210404776,01/21/2021 12:00:00 AM,01/19/2021 12:00:00 AM,1600,4,Hollenbeck,497,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,1400 S DE LA TORRE WY,NaN,34.0166,-118.2058
276580,212000771,05/28/2021 12:00:00 AM,05/28/2021 12:00:00 AM,1930,20,Olympic,2056,2,888,TRESPASSING,...,IC,Invest Cont,888.0,998.0,NaN,NaN,900 S BERENDO ST,NaN,34.0527,-118.2937
276581,211208872,03/19/2021 12:00:00 AM,03/19/2021 12:00:00 AM,1105,12,77th Street,1218,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,58TH ST,FIGUEROA ST,33.9897,-118.2827
276582,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,5,Harbor,564,2,434,FALSE IMPRISONMENT,...,AA,Adult Arrest,434.0,NaN,NaN,NaN,200 W 2ND ST,NaN,33.7424,-118.2814
276583,212005847,02/22/2021 12:00:00 AM,02/22/2021 12:00:00 AM,1200,20,Olympic,2034,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,3300 W 8TH ST,NaN,34.0596,-118.3022

In [ ]:
df_1[(df_1['AREA NAME']=='Harbor') | (df_1['AREA NAME']=='Hollywood')]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
17,200506268,02/22/2020 12:00:00 AM,02/22/2020 12:00:00 AM,1900,5,Harbor,511,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440.0,624.0,NaN,NaN,PACIFIC COAST,VERMONT,33.7926,-118.3043
41,200608399,03/28/2020 12:00:00 AM,03/27/2020 12:00:00 AM,1700,6,Hollywood,615,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,LAKE HOLLYWOOD,WONDER VIEW,34.1322,-118.3384
50,200611450,06/16/2020 12:00:00 AM,06/15/2020 12:00:00 AM,1800,6,Hollywood,636,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,6500 YUCCA ST,NaN,34.1039,-118.3311
132,200610699,05/27/2020 12:00:00 AM,05/24/2020 12:00:00 AM,1730,6,Hollywood,648,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440.0,NaN,NaN,NaN,5600 CARLTON WY,NaN,34.1005,-118.3115
160,200608304,03/24/2020 12:00:00 AM,03/24/2020 12:00:00 AM,1550,6,Hollywood,666,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,HOLLYWOOD,VINE,34.0944,-118.3277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276522,210607188,03/18/2021 12:00:00 AM,01/24/2021 12:00:00 AM,1000,6,Hollywood,625,2,649,DOCUMENT FORGERY / STOLEN FELONY,...,IC,Invest Cont,649.0,NaN,NaN,NaN,6700 W HILLPARK DR,NaN,34.1177,-118.3385
276524,210504649,01/17/2021 12:00:00 AM,01/17/2021 12:00:00 AM,900,5,Harbor,564,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,AO,Adult Other,440.0,NaN,NaN,NaN,200 W SANTA CRUZ ST,NaN,33.7410,-118.2838
276562,210500569,03/02/2021 12:00:00 AM,03/02/2021 12:00:00 AM,2053,5,Harbor,557,2,890,FAILURE TO YIELD,...,IC,Invest Cont,890.0,NaN,NaN,NaN,1ST ST,GAFFEY ST,33.7433,-118.2923
276574,210610209,05/25/2021 12:00:00 AM,05/25/2021 12:00:00 AM,813,6,Hollywood,645,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,6800 HOLLYWOOD BL,NaN,34.1016,-118.3391
276582,210506531,03/04/2021 12:00:00 AM,03/04/2021 12:00:00 AM,2210,5,Harbor,564,2,434,FALSE IMPRISONMENT,...,AA,Adult Arrest,434.0,NaN,NaN,NaN,200 W 2ND ST,NaN,33.7424,-118.2814